services:

  mysql:
    image: mysql:8
    container_name: stock-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_project
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: stock-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    container_name: stock-worker
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: stock-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data: